package Presentación;
import Datos.cls_clientes;
import java.util.LinkedList;
import Negocio.cls_validar_cliente;
import javax.swing.JOptionPane;

public class frm_Restaurante extends javax.swing.JFrame {
    LinkedList<cls_clientes>  clientes = new LinkedList<>(); //Lista de clientes 
    cls_validar_cliente objValidar = new cls_validar_cliente(); //  Instancia unica
    boolean sw;
    int posicion;
    
    /**
     * Creates new form frm_Restaurante
     */
    public frm_Restaurante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_contacto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_nuevo = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_consultar = new javax.swing.JButton();
        btn_CambiarEstado = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt_detalle = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btn_nuevoPedido = new javax.swing.JButton();
        btn_generarPedido = new javax.swing.JButton();
        btn_consultarCliente = new javax.swing.JButton();
        txt_nombrePedido = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_idPedido = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(190, 144, 237));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORMULARIO DE REGISTRO DE PEDIDOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 550, 65));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 100));

        jTabbedPane1.setBackground(new java.awt.Color(247, 176, 176));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Correo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 70, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));
        jPanel2.add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 230, 30));

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        jPanel2.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 230, 30));
        jPanel2.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 230, 30));
        jPanel2.add(txt_contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 230, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Identificación:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 120, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Nombres:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 120, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Contacto:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 120, -1));

        jPanel4.setBackground(new java.awt.Color(163, 163, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_nuevo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        jPanel4.add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 140, 30));

        btn_guardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        jPanel4.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 140, 30));

        btn_consultar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_consultar.setText("Consultar");
        btn_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarActionPerformed(evt);
            }
        });
        jPanel4.add(btn_consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 140, 30));

        btn_CambiarEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_CambiarEstado.setText("Cambiar estado");
        btn_CambiarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CambiarEstadoActionPerformed(evt);
            }
        });
        jPanel4.add(btn_CambiarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 140, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 260, 340));

        jTabbedPane1.addTab("Clientes", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_detalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_detalleActionPerformed(evt);
            }
        });
        jPanel3.add(txt_detalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 230, 100));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Total a pagar:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 120, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Nombres:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 120, -1));

        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });
        jPanel3.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 230, 30));

        jPanel5.setBackground(new java.awt.Color(163, 163, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_nuevoPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_nuevoPedido.setText("Nuevo pedido");
        btn_nuevoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoPedidoActionPerformed(evt);
            }
        });
        jPanel5.add(btn_nuevoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 140, 30));

        btn_generarPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_generarPedido.setText("Generar pedido");
        btn_generarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarPedidoActionPerformed(evt);
            }
        });
        jPanel5.add(btn_generarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 140, 30));

        btn_consultarCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_consultarCliente.setText("Consultar cliente");
        btn_consultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarClienteActionPerformed(evt);
            }
        });
        jPanel5.add(btn_consultarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 140, 30));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 260, 340));

        txt_nombrePedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombrePedidoActionPerformed(evt);
            }
        });
        jPanel3.add(txt_nombrePedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 230, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Identificación:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 120, -1));

        txt_idPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idPedidoActionPerformed(evt);
            }
        });
        jPanel3.add(txt_idPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 230, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Detalle orden:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 120, -1));

        jTabbedPane1.addTab("Pedidos", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 780, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        objValidar.validarDatosEntrada(
                txt_id.getText(),
                txt_nombre.getText(),
                txt_contacto.getText(),
                txt_correo.getText());
        if(objValidar.getVal() == true){
            clientes.add(new cls_clientes(
                    txt_id.getText(),
                    txt_nombre.getText(),
                    txt_contacto.getText(),
                    txt_correo.getText()));
        }
        JOptionPane.showMessageDialog(null, objValidar.getMsn());
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_CambiarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CambiarEstadoActionPerformed
        fnt_consultar(txt_id.getText(), "2");
    }//GEN-LAST:event_btn_CambiarEstadoActionPerformed
    
    private void fnt_nuevo_cliente(){
        txt_contacto.setText("");
        txt_correo.setText("");
        txt_id.setText("");
        txt_nombre.setText("");
        txt_id.requestFocus();
    }
    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
       fnt_nuevo_cliente();
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed
    
    private void fnt_consultar(String id, String tipo){
        sw = false;
        posicion = 0;
        for(int i = 0; i < clientes.size(); i++){
            if(id.equals(clientes.get(i).getIdStr())){
                sw = true;
                posicion = i;
                break;
            }
        }
        if(sw == false){
            JOptionPane.showMessageDialog(null, "No se encontraron datos");
        }else{
            if(tipo.equals("1")){
                txt_contacto.setText(clientes.get(posicion).getContactoStr());
                txt_correo.setText(clientes.get(posicion).getCorreoStr());
                txt_nombre.setText(clientes.get(posicion).getNombreStr());
            }
            if(tipo.equals("2")){
               clientes.get(posicion).setEstado(1);
               JOptionPane.showMessageDialog(null, "Estado actualizado");
            }
          
        }
    }
    private void btn_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarActionPerformed
        fnt_consultar(txt_id.getText(), "1");
    }//GEN-LAST:event_btn_consultarActionPerformed

    private void txt_detalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_detalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_detalleActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void btn_nuevoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nuevoPedidoActionPerformed

    private void btn_generarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_generarPedidoActionPerformed

    private void btn_consultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_consultarClienteActionPerformed

    private void txt_nombrePedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombrePedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombrePedidoActionPerformed

    private void txt_idPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Restaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CambiarEstado;
    private javax.swing.JButton btn_consultar;
    private javax.swing.JButton btn_consultarCliente;
    private javax.swing.JButton btn_generarPedido;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_nuevoPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txt_contacto;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_detalle;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_idPedido;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombrePedido;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
